version: "3.1"

services:
  dc1:
    image: samba:almalinux
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.almalinux
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDERS: 8.8.8.8
      DNS_BACKEND: BIND9_DLZ
    volumes:
      - dc1-local-samba:/usr/local/samba

volumes:
  dc1-local-samba: