version: "3.8"

services:
  dc1:
    image: samba:almalinux
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.almalinux
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_BACKEND: BIND9_DLZ
      DNS_FORWARDERS: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    command: bash -c "
      set -x &&
      samba-domain-provision &&
      echo -e \"172.16.238.20 DC2.dgs.net DC2\" >> /etc/hosts &&
      echo -e \"172.16.238.30 DC3.dgs.net DC3\" >> /etc/hosts &&
      echo -e \"172.16.238.40 DC4.dgs.net DC4\" >> /etc/hosts &&
      echo -e \"nameserver 172.16.238.20\" >> /etc/resolv.conf &&
      echo -e \"nameserver 172.16.238.30\" >> /etc/resolv.conf &&
      echo -e \"nameserver 172.16.238.40\" >> /etc/resolv.conf &&
      samba -F"
    volumes:
      - dc1-local-samba:/usr/local/samba

    networks:
      static-network:
        ipv4_address: 172.16.238.10

  dc2:
    image: samba:ubuntu
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu
    container_name: dc2
    hostname: DC2
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_BACKEND: BIND9_DLZ
      DNS_FORWARDERS: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    command: bash -c "
      set -x &&
      samba-domain-join DC1 &&
      echo -e \"172.16.238.10 DC1.dgs.net DC1\" >> /etc/hosts &&
      echo -e \"172.16.238.30 DC3.dgs.net DC3\" >> /etc/hosts &&
      echo -e \"172.16.238.40 DC4.dgs.net DC4\" >> /etc/hosts &&
      echo -e \"nameserver 172.16.238.10\" >> /etc/resolv.conf &&
      echo -e \"nameserver 172.16.238.30\" >> /etc/resolv.conf &&
      echo -e \"nameserver 172.16.238.40\" >> /etc/resolv.conf &&
      samba -F"
    volumes:
      - dc2-local-samba:/usr/local/samba
    networks:
      static-network:
        ipv4_address: 172.16.238.20

  dc3:
    image: samba:rockylinux
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.rockylinux
    container_name: dc3
    hostname: DC3
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_BACKEND: BIND9_DLZ
      DNS_FORWARDERS: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    command: bash -c "
      set -x &&
      samba-domain-join DC1 &&
      echo -e \"172.16.238.10 DC1.dgs.net DC1\" >> /etc/hosts &&
      echo -e \"172.16.238.20 DC2.dgs.net DC2\" >> /etc/hosts &&
      echo -e \"172.16.238.40 DC4.dgs.net DC4\" >> /etc/hosts &&
      echo -e \"nameserver 172.16.238.10\" >> /etc/resolv.conf &&
      echo -e \"nameserver 172.16.238.20\" >> /etc/resolv.conf &&
      echo -e \"nameserver 172.16.238.40\" >> /etc/resolv.conf &&
      samba -F"
    volumes:
      - dc3-local-samba:/usr/local/samba
    networks:
      static-network:
        ipv4_address: 172.16.238.30

  dc4:
    image: samba:debian
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian
    container_name: dc4
    hostname: DC4
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_BACKEND: BIND9_DLZ
      DNS_FORWARDERS: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    command: bash -c "
      set -x &&
      samba-domain-join DC1 &&
      echo -e \"172.16.238.10 DC1.dgs.net DC1\" >> /etc/hosts &&
      echo -e \"172.16.238.20 DC2.dgs.net DC2\" >> /etc/hosts &&
      echo -e \"172.16.238.30 DC3.dgs.net DC3\" >> /etc/hosts &&
      echo -e \"nameserver 172.16.238.10\" >> /etc/resolv.conf &&
      echo -e \"nameserver 172.16.238.20\" >> /etc/resolv.conf &&
      echo -e \"nameserver 172.16.238.30\" >> /etc/resolv.conf &&
      samba -F"
    volumes:
      - dc4-local-samba:/usr/local/samba
    networks:
      static-network:
        ipv4_address: 172.16.238.40

volumes:
  dc1-local-samba:
  dc2-local-samba:
  dc3-local-samba:
  dc4-local-samba:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.16.238.0/24