#!/usr/bin/env bash

# Exit if any error
set -euo pipefail

# Wait for network interface
until ip a | grep 'scope global' >/dev/null 2>&1; do
  echo 'Waiting for network interface..'
  sleep 1
done

SERVER_IP=$(ip a | grep 'scope global' | head -n1 | awk '{print $2}' | awk -F / '{print $1}')
SEARCH_DOMAIN=$(echo "${REALM}" | tr [:upper:] [:lower:])

# Update resolv.conf based on current network info
if ! grep -q "${SEARCH_DOMAIN}" /etc/resolv.conf; then
  echo -e "search ${SEARCH_DOMAIN}\nnameserver ${SERVER_IP}" >/etc/resolv.conf
fi

# Update /etc/hosts file with current hostname and domain
if ! grep -q "${SEARCH_DOMAIN}" /etc/hosts; then
  echo -e "${SERVER_IP} $(hostname).${SEARCH_DOMAIN} $(hostname)" >>/etc/hosts
fi

# Update krb5 file with compiled files
if ! grep -q "${SEARCH_DOMAIN}" /etc/krb5.conf; then
  cat "${SAMBA_PATH:-/usr/local/samba}/private/krb5.conf" >/etc/krb5.conf
fi

# Configure bind files and start service for BIND9_DLZ as DNS_BACKEND
if [[ "${DNS_BACKEND:-SAMBA_INTERNAL}" == 'BIND9_DLZ' ]]; then update-and-start-bind; fi
